
project_name: Ansible_Project
template_name: csr_updates
filter: device_family
filter_value: Cisco Cloud Services Router 1000V
cli_template: |
  !
  no snmp-server host 10.93.141.30 version 2c RO
  no snmp-server host 10.93.130.50 version 2c RW
  !
  ntp server 171.68.48.78
  no ntp server 171.68.48.80
